name: Danger

on:
  pull_request:
    branches: [ develop, main ]

jobs:
  check:
    name: Danger Check
    runs-on: ubuntu-latest
    
    permissions:
      issues: write
      pull-requests: write
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Bundle install
        run: bundle install
      
      - name: Run Danger
        run: bundle exec danger --verbose
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
